FROM python:3.12-slim

WORKDIR /app

COPY comparing_models.py .
COPY requirements.txt .
COPY entrypoint.sh .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "comparing_models.py"]
